/*
 * field.c -- F_p arithmetic for p = 5 * 2^248 - 1 (251-bit prime)
 *
 * 5 limbs of 51 bits, unsaturated. Montgomery form, working modulus 2p.
 * Adapted from reference/field/fp_p5248_64.c (generated by monty.py).
 */
#include "field.h"
#include <string.h>
#include <stdio.h>

/* ── internal types ──────────────────────────────────────────── */

typedef int64_t  sspint;
typedef uint64_t spint;
typedef __int128 dpint;
typedef unsigned __int128 udpint;

#define Q      ((spint)1 << FIELD_RADIX)   /* 2^51 */
#define MASK   (Q - 1)                      /* 0x7ffffffffffff */
#define P4     0x500000000000ULL            /* top limb of 2p */

/* ── internal prototypes ─────────────────────────────────────── */

static spint prop(spint n[5]);
static int   flatten(spint n[5]);
static int   modfsb(spint n[5]);
static void  nres(const spint m[5], spint n[5]);
static void  redc(const spint n[5], spint m[5]);
static void  modadd(const spint a[5], const spint b[5], spint c[5]);
static void  modsub(const spint a[5], const spint b[5], spint c[5]);
static void  modneg(const spint b[5], spint c[5]);
static void  modmul(const spint a[5], const spint b[5], spint c[5]);
static void  modsqr(const spint a[5], spint c[5]);
static void  modpro(const spint w[5], spint z[5]);
static void  modinv(const spint x[5], const spint h[5], spint z[5]);
static void  modsqrt(const spint x[5], const spint h[5], spint r[5]);
static int   modis0(const spint a[5]);
static int   modis1(const spint a[5]);
static int   modqr(const spint h[5], const spint x[5]);
static void  modcsw(int b, volatile spint g[5], volatile spint f[5]);
static void  modcmv(int b, const spint g[5], volatile spint f[5]);

/* ── carry propagation ───────────────────────────────────────── */

static spint prop(spint n[5]) {
    sspint carry = (sspint)n[0];
    carry >>= FIELD_RADIX;
    n[0] &= MASK;
    for (int i = 1; i < 4; i++) {
        carry += (sspint)n[i];
        n[i] = (spint)carry & MASK;
        carry >>= FIELD_RADIX;
    }
    n[4] += (spint)carry;
    /* check underflow: top 13 bits of n[4] */
    return -((n[4] >> 1) >> 62u);
}

static int flatten(spint n[5]) {
    spint carry = prop(n);
    n[0] -= (spint)1u & carry;
    n[4] += (P4) & carry;
    (void)prop(n);
    return (int)(carry & 1);
}

static int modfsb(spint n[5]) {
    n[0] += (spint)1u;
    n[4] -= P4;
    return flatten(n);
}

/* ── Montg. conversion ───────────────────────────────────────── */

static void nres(const spint m[5], spint n[5]) {
    /* R^2 mod 2p */
    static const spint c[5] = {
        0x4cccccccccf5cULL, 0x1999999999999ULL, 0x3333333333333ULL,
        0x6666666666666ULL, 0xcccccccccccuLL
    };
    modmul(m, c, n);
}

static void redc(const spint n[5], spint m[5]) {
    spint c[5];
    c[0] = 1;
    for (int i = 1; i < 5; i++) c[i] = 0;
    modmul(n, c, m);
    (void)modfsb(m);
}

/* ── modular arithmetic (all assume Montg. inputs) ────────────── */

static void modadd(const spint a[5], const spint b[5], spint c[5]) {
    c[0] = a[0] + b[0];
    c[1] = a[1] + b[1];
    c[2] = a[2] + b[2];
    c[3] = a[3] + b[3];
    c[4] = a[4] + b[4];
    c[0] += (spint)2u;
    c[4] -= (spint)0xa00000000000ULL;
    spint carry = prop(c);
    c[0] -= (spint)2u & carry;
    c[4] += ((spint)0xa00000000000ULL) & carry;
    (void)prop(c);
}

static void modsub(const spint a[5], const spint b[5], spint c[5]) {
    c[0] = a[0] - b[0];
    c[1] = a[1] - b[1];
    c[2] = a[2] - b[2];
    c[3] = a[3] - b[3];
    c[4] = a[4] - b[4];
    spint carry = prop(c);
    c[0] -= (spint)2u & carry;
    c[4] += ((spint)0xa00000000000ULL) & carry;
    (void)prop(c);
}

static void modneg(const spint b[5], spint c[5]) {
    c[0] = (spint)0 - b[0];
    c[1] = (spint)0 - b[1];
    c[2] = (spint)0 - b[2];
    c[3] = (spint)0 - b[3];
    c[4] = (spint)0 - b[4];
    spint carry = prop(c);
    c[0] -= (spint)2u & carry;
    c[4] += ((spint)0xa00000000000ULL) & carry;
    (void)prop(c);
}

static void modmul(const spint a[5], const spint b[5], spint c[5]) {
    dpint t = 0;
    spint mask = MASK;
    spint p4 = P4;

    t += (dpint)a[0] * b[0];
    spint v0 = ((spint)t & mask); t >>= FIELD_RADIX;
    t += (dpint)a[0] * b[1]; t += (dpint)a[1] * b[0];
    spint v1 = ((spint)t & mask); t >>= FIELD_RADIX;
    t += (dpint)a[0] * b[2]; t += (dpint)a[1] * b[1]; t += (dpint)a[2] * b[0];
    spint v2 = ((spint)t & mask); t >>= FIELD_RADIX;
    t += (dpint)a[0] * b[3]; t += (dpint)a[1] * b[2]; t += (dpint)a[2] * b[1]; t += (dpint)a[3] * b[0];
    spint v3 = ((spint)t & mask); t >>= FIELD_RADIX;
    t += (dpint)a[0] * b[4]; t += (dpint)a[1] * b[3]; t += (dpint)a[2] * b[2];
    t += (dpint)a[3] * b[1]; t += (dpint)a[4] * b[0];
    t += (dpint)v0 * (dpint)p4;
    spint v4 = ((spint)t & mask); t >>= FIELD_RADIX;
    t += (dpint)a[1] * b[4]; t += (dpint)a[2] * b[3]; t += (dpint)a[3] * b[2]; t += (dpint)a[4] * b[1];
    t += (dpint)v1 * (dpint)p4;
    c[0] = ((spint)t & mask); t >>= FIELD_RADIX;
    t += (dpint)a[2] * b[4]; t += (dpint)a[3] * b[3]; t += (dpint)a[4] * b[2];
    t += (dpint)v2 * (dpint)p4;
    c[1] = ((spint)t & mask); t >>= FIELD_RADIX;
    t += (dpint)a[3] * b[4]; t += (dpint)a[4] * b[3];
    t += (dpint)v3 * (dpint)p4;
    c[2] = ((spint)t & mask); t >>= FIELD_RADIX;
    t += (dpint)a[4] * b[4];
    t += (dpint)v4 * (dpint)p4;
    c[3] = ((spint)t & mask); t >>= FIELD_RADIX;
    c[4] = (spint)t;
}

static void modsqr(const spint a[5], spint c[5]) {
    udpint tot;
    udpint t = 0;
    spint mask = MASK;
    spint p4 = P4;

    tot = (udpint)a[0] * a[0]; t = tot;
    spint v0 = ((spint)t & mask); t >>= FIELD_RADIX;
    tot = (udpint)a[0] * a[1]; tot *= 2; t += tot;
    spint v1 = ((spint)t & mask); t >>= FIELD_RADIX;
    tot = (udpint)a[0] * a[2]; tot *= 2; tot += (udpint)a[1] * a[1]; t += tot;
    spint v2 = ((spint)t & mask); t >>= FIELD_RADIX;
    tot = (udpint)a[0] * a[3]; tot += (udpint)a[1] * a[2]; tot *= 2; t += tot;
    spint v3 = ((spint)t & mask); t >>= FIELD_RADIX;
    tot = (udpint)a[0] * a[4]; tot += (udpint)a[1] * a[3]; tot *= 2; tot += (udpint)a[2] * a[2]; t += tot;
    t += (udpint)v0 * p4;
    spint v4 = ((spint)t & mask); t >>= FIELD_RADIX;
    tot = (udpint)a[1] * a[4]; tot += (udpint)a[2] * a[3]; tot *= 2; t += tot;
    t += (udpint)v1 * p4;
    c[0] = ((spint)t & mask); t >>= FIELD_RADIX;
    tot = (udpint)a[2] * a[4]; tot *= 2; tot += (udpint)a[3] * a[3]; t += tot;
    t += (udpint)v2 * p4;
    c[1] = ((spint)t & mask); t >>= FIELD_RADIX;
    tot = (udpint)a[3] * a[4]; tot *= 2; t += tot;
    t += (udpint)v3 * p4;
    c[2] = ((spint)t & mask); t >>= FIELD_RADIX;
    tot = (udpint)a[4] * a[4]; t += tot;
    t += (udpint)v4 * p4;
    c[3] = ((spint)t & mask); t >>= FIELD_RADIX;
    c[4] = (spint)t;
}

/* ── exponentiation helpers ───────────────────────────────────── */

static void modsqr_n(spint a[5], int n) {
    for (int i = 0; i < n; i++) modsqr(a, a);
}

static void modpro(const spint w[5], spint z[5]) {
    spint x[5], t0[5], t1[5], t2[5], t3[5];
    spint cpy_buf[5]; /* replacement for modcpy macro */

    memcpy(x, w, sizeof(spint) * 5);
    modsqr(x, z);
    modmul(x, z, t0);
    modsqr(t0, z);
    modmul(x, z, z);
    modsqr(z, t1); modsqr(t1, t3); modsqr(t3, t2);

    memcpy(cpy_buf, t2, sizeof(spint) * 5);
    modsqr_n(cpy_buf, 3);
    modmul(t2, cpy_buf, t2);

    memcpy(cpy_buf, t2, sizeof(spint) * 5);
    modsqr_n(cpy_buf, 6);
    modmul(t2, cpy_buf, t2);

    memcpy(cpy_buf, t2, sizeof(spint) * 5);
    modsqr_n(cpy_buf, 2);
    modmul(t3, cpy_buf, t3); modsqr_n(t3, 13);
    modmul(t2, t3, t2);

    memcpy(cpy_buf, t2, sizeof(spint) * 5);
    modsqr_n(cpy_buf, 27);
    modmul(t2, cpy_buf, t2);
    modmul(z, t2, z);

    memcpy(cpy_buf, z, sizeof(spint) * 5);
    modsqr_n(cpy_buf, 4);
    modmul(t1, cpy_buf, t1);
    modmul(t0, t1, t0);
    modmul(t1, t0, t1);
    modmul(t0, t1, t0);
    modmul(t1, t0, t2);
    modmul(t0, t2, t0);
    modmul(t1, t0, t1);
    modsqr_n(t1, 63);
    modmul(t0, t1, t1);
    modsqr_n(t1, 64);
    modmul(t0, t1, t0);
    modsqr_n(t0, 57);
    modmul(z, t0, z);
}

static void modinv(const spint x[5], const spint h[5], spint z[5]) {
    spint s[5], t[5];
    if (h == NULL) {
        modpro(x, t);
    } else {
        memcpy(t, h, sizeof(spint) * 5);
    }
    memcpy(s, x, sizeof(spint) * 5);
    modsqr_n(t, 2);
    modmul(s, t, z);
}

static void modsqrt(const spint x[5], const spint h[5], spint r[5]) {
    spint y[5], s[5];
    if (h == NULL) {
        modpro(x, y);
    } else {
        memcpy(y, h, sizeof(spint) * 5);
    }
    modmul(y, x, s);
    memcpy(r, s, sizeof(spint) * 5);
}

/* ── tests ────────────────────────────────────────────────────── */

static int modis0(const spint a[5]) {
    spint c[5], d = 0;
    redc(a, c);
    for (int i = 0; i < 5; i++) d |= c[i];
    return ((spint)1 & ((d - (spint)1) >> FIELD_RADIX));
}

static int modis1(const spint a[5]) {
    spint c[5], d = 0;
    redc(a, c);
    for (int i = 1; i < 5; i++) d |= c[i];
    spint c0 = (spint)c[0];
    return ((spint)1 & ((d - (spint)1) >> FIELD_RADIX) &
            (((c0 ^ (spint)1) - (spint)1) >> FIELD_RADIX));
}

static int modqr(const spint h[5], const spint x[5]) {
    spint r[5];
    if (h == NULL) {
        modpro(x, r);
        modsqr(r, r);
    } else {
        modsqr(h, r);
    }
    modmul(r, x, r);
    return modis1(r) | modis0(x);
}

/* ── constant-time ops ───────────────────────────────────────── */

static void modcsw(int b, volatile spint g[5], volatile spint f[5]) {
    spint c0, c1, s, t, w;
    spint r = 0x3cc3c33c5aa5a55aULL;
    c0 = (1 - b) + r;
    c1 = b + r;
    for (int i = 0; i < 5; i++) {
        s = g[i]; t = f[i]; w = r * (t + s);
        f[i] = c0 * t + c1 * s;
        f[i] -= w;
        g[i] = c0 * s + c1 * t;
        g[i] -= w;
    }
}

static void modcmv(int b, const spint g[5], volatile spint f[5]) {
    spint c0, c1, s, t;
    spint r = 0x3cc3c33c5aa5a55aULL;
    c0 = (1 - b) + r;
    c1 = b + r;
    for (int i = 0; i < 5; i++) {
        s = g[i]; t = f[i];
        f[i] = c0 * t + c1 * s;
        f[i] -= r * (t + s);
    }
}

/* ── serialisation ────────────────────────────────────────────── */

static void modshl(unsigned int n, spint a[5]) {
    a[4] = ((a[4] << n)) | (a[3] >> (FIELD_RADIX - n));
    for (int i = 3; i > 0; i--)
        a[i] = ((a[i] << n) & MASK) | (a[i - 1] >> (FIELD_RADIX - n));
    a[0] = (a[0] << n) & MASK;
}

static int modshr(unsigned int n, spint a[5]) {
    spint r = a[0] & (((spint)1 << n) - (spint)1);
    for (int i = 0; i < 4; i++)
        a[i] = (a[i] >> n) | ((a[i + 1] << (FIELD_RADIX - n)) & MASK);
    a[4] = a[4] >> n;
    return (int)r;
}

/* ════════════════════════════════════════════════════════════════
 *  PUBLIC API
 * ════════════════════════════════════════════════════════════════ */

void fp_set_zero(fp_t a) {
    memset(a, 0, sizeof(fp_t));
}

void fp_set_one(fp_t a) {
    a[0] = 1;
    for (int i = 1; i < FIELD_WORDS; i++) a[i] = 0;
    nres(a, a);
}

void fp_set_small(fp_t a, uint64_t val) {
    a[0] = (spint)val;
    for (int i = 1; i < FIELD_WORDS; i++) a[i] = 0;
    nres(a, a);
}

void fp_copy(fp_t dst, const fp_t src) {
    memcpy(dst, src, sizeof(fp_t));
}

void fp_random(fp_t a) {
    /* Simple: fill with random bytes and reduce mod 2p.
     * For production: use a proper CSPRNG. */
    uint8_t buf[64];
    FILE *f = fopen("/dev/urandom", "rb");
    if (f) { fread(buf, 1, 64, f); fclose(f); }
    else {
        /* fallback: very weak, test only */
        for (int i = 0; i < 64; i++) buf[i] = (uint8_t)(i * 1103515245 + 12345);
    }
    /* reduce: interpret as unsigned little-endian, mod 2p */
    spint tmp[5] = {0};
    for (int i = 0; i < 32; i++) {
        modshl(8, tmp);
        tmp[0] += (spint)buf[i];
    }
    (void)modfsb(tmp);
    nres(tmp, a);
}

/* ── arithmetic ───────────────────────────────────────────────── */

void fp_add(fp_t r, const fp_t a, const fp_t b)  { modadd(a, b, r); }
void fp_sub(fp_t r, const fp_t a, const fp_t b)  { modsub(a, b, r); }
void fp_neg(fp_t r, const fp_t a)                { modneg(a, r); }
void fp_mul(fp_t r, const fp_t a, const fp_t b)  { modmul(a, b, r); }
void fp_sqr(fp_t r, const fp_t a)                { modsqr(a, r); }

void fp_inv(fp_t r, const fp_t a) {
    modinv(a, NULL, r);
}

void fp_mul_small(fp_t r, const fp_t a, uint32_t val) {
    spint t[5];
    fp_set_small(t, val);
    modmul(a, t, r);
}

void fp_double(fp_t r, const fp_t a) {
    fp_add(r, a, a);
}

void fp_sub_x2(fp_t r, const fp_t a, const fp_t b) {
    fp_t doubled;
    fp_double(doubled, a);
    fp_sub(r, doubled, b);
}

/* ── tests ────────────────────────────────────────────────────── */

int fp_is_zero(const fp_t a)  { return modis0(a); }
int fp_is_one(const fp_t a)   { return modis1(a); }

int fp_is_equal(const fp_t a, const fp_t b) {
    spint c[5], d[5];
    redc(a, c);
    redc(b, d);
    int eq = 1;
    for (int i = 0; i < 5; i++)
        eq &= (int)(((c[i] ^ d[i]) - 1) >> FIELD_RADIX) & 1;
    return eq;
}

int fp_is_square(const fp_t a) {
    return modqr(NULL, a);
}

/* ── sqrt ─────────────────────────────────────────────────────── */

void fp_exp3div4(fp_t out, const fp_t a) {
    modpro(a, out);
}

void fp_sqrt(fp_t r, const fp_t a) {
    modsqrt(a, NULL, r);
}

/* ── constant-time ────────────────────────────────────────────── */

void fp_cswap(fp_t a, fp_t b, uint32_t ctl) {
    modcsw((int)(ctl & 0x1), a, b);
}

void fp_cmov(fp_t r, const fp_t a, uint32_t ctl) {
    /* use cswap trick: copy a to r, then cswap(r, original) if ctl=0 */
    /* simpler: conditional move using modcmv */
    modcmv((int)(ctl & 0x1), a, r);
}

/* ── serialisation ────────────────────────────────────────────── */

void fp_encode(uint8_t out[FIELD_BYTES], const fp_t a) {
    spint c[5];
    redc(a, c);
    for (int i = FIELD_BYTES - 1; i >= 0; i--) {
        out[i] = (uint8_t)(c[0] & 0xff);
        (void)modshr(8, c);
    }
}

int fp_decode(fp_t a, const uint8_t in[FIELD_BYTES]) {
    memset(a, 0, sizeof(fp_t));
    for (int i = 0; i < FIELD_BYTES; i++) {
        modshl(8, a);
        a[0] += (spint)in[i];
    }
    int res = modfsb(a);
    nres(a, a);
    return res;
}
